using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Tank : MonoBehaviour
{
    [SerializeField] private Transform _shootPoint;
    [SerializeField] private Bullet _buletTemplate;
    [SerializeField] private float _delayBetweemShoots;

    private float _timeAfterShoot;

    private void Update()
    {
        _timeAfterShoot += Time.deltaTime;
        if(Input.GetMouseButton(0))
        {
            if(_timeAfterShoot>_delayBetweemShoots)
            {
                Shoot();
                _timeAfterShoot = 0;
            }
                
            
        }
    }

    private void Shoot()
    {
        Instantiate(_buletTemplate, _shootPoint.position, Quaternion.identity);
    }
}

